In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [14]:
np.array([[1,2,3,4],[1,3,4,5],[2,2,4,4]],dtype=float)

array([[1., 2., 3., 4.],
       [1., 3., 4., 5.],
       [2., 2., 4., 4.]])

In [32]:
np.arange(10,41,2,dtype=float).reshape(4,4)

array([[10., 12., 14., 16.],
       [18., 20., 22., 24.],
       [26., 28., 30., 32.],
       [34., 36., 38., 40.]])

In [31]:
np.arange(10,41,2,dtype=float).reshape(2,2,2,2)

array([[[[10., 12.],
         [14., 16.]],

        [[18., 20.],
         [22., 24.]]],


       [[[26., 28.],
         [30., 32.]],

        [[34., 36.],
         [38., 40.]]]])

In [35]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.random.random((3,4))

array([[0.69019848, 0.74226284, 0.13011119, 0.55230159],
       [0.36363343, 0.23910585, 0.79799683, 0.36296062],
       [0.90127928, 0.69458945, 0.30201159, 0.36060136]])

In [44]:
np.random.random((3,4,5))

array([[[0.48741352, 0.62748847, 0.96740554, 0.39174488, 0.144166  ],
        [0.21732223, 0.1439289 , 0.26446287, 0.04108821, 0.94470871],
        [0.73342754, 0.35075022, 0.62651775, 0.14339556, 0.36810511],
        [0.7746308 , 0.30592293, 0.07134547, 0.55793196, 0.26968321]],

       [[0.26887799, 0.24117136, 0.04914496, 0.41266468, 0.92103489],
        [0.53156167, 0.40176988, 0.14852043, 0.87583414, 0.51512469],
        [0.31320444, 0.06639395, 0.59540061, 0.45421647, 0.92110911],
        [0.5575937 , 0.73461189, 0.97797314, 0.37431807, 0.28462816]],

       [[0.25914649, 0.05374045, 0.37268964, 0.2140986 , 0.96707316],
        [0.10775668, 0.90375319, 0.36322011, 0.94079135, 0.56702916],
        [0.07968041, 0.52864195, 0.03693675, 0.9676031 , 0.67033024],
        [0.67923791, 0.22822944, 0.91195727, 0.66351699, 0.48028155]]])

In [47]:
np.linspace(10,-10,8)

array([ 10.        ,   7.14285714,   4.28571429,   1.42857143,
        -1.42857143,  -4.28571429,  -7.14285714, -10.        ])

In [53]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [61]:
a1 = np.arange(10).reshape(5,2)

In [62]:
a1.shape

(5, 2)