#### What is Numpy?
    
   1. Numpy is a fundamental package for scientific computing in python. It is basically a python mathematical library used for mathematical calculations. It provides a multidimensional array object, various derived objects (such as masked arrays and matrices and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
   
   2. At the core of the NumPy package, is the ndarray object. This creates n-dimensional arrays of homogeneous data types. Homogeneous array means the data types of all the array items are same.
   
   3. Numpy is built on c language.

#### Numpy Arrays Vs Python Sequences:

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

# Creating numpy array


In [1]:
import numpy as np
#np.array
#Imporing numpy library as we use the word np in place of numpy.

In [2]:
#creating numpy array.
#np.array is used to create an array, it accpets the list of values and creates a numpy array.
#It is also called as vectors.

a = np.array([1,2,3])
print(a)
print(type(a))

#it is a 1D array.

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
#Creating 2D array:
#it is also called matrix bcoz it contains rows and columns.
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Creating 3D array:
#it is also called tensor.
c = np.array([[[1,2],[1,3]],[[5,6],[7,8]]])
print(c)

In [5]:
#Creating our own datatype array:
#keyword used is dtype.
np.array([1,2,3], dtype=float)
np.array([1,2,3], dtype=bool)
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [6]:
# Creating an empty array(nan).
a = np.nan
print(a)  #Prints an 'nan' value
b = np.nan * np.empty(10)  #creates an array of 10 'nan' values.
b

nan


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [7]:
#np.arange()
#it is another method to create an array.
#It works like a loop with the range.
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [9]:
#reshape()
#it creates a matrix for a list taking the row and column size as a parameter.
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [10]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [11]:
#np.ones and np.zeros
#it creates an matrix of given size in which all the values are zeros or ones.
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
#np.random
#it also creates an array in the form of matrix by taking the size and generates the random numbers between 0 and 1.
np.random.random((3,4))

array([[0.75091179, 0.97237805, 0.91347849, 0.82260772],
       [0.29441107, 0.67132732, 0.58855222, 0.65368317],
       [0.28226152, 0.75942539, 0.77212593, 0.1425926 ]])

In [14]:
#np.linspace (linear space)
#generates the points within a range with equally distributed parts.
np.linspace(-10,10,10, dtype=int) #by default dtype:float.

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [15]:
#np.identity()
#creates an identity matrix.
np.identity(3)
#it will create a 3x3 matrix.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes


In [16]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [17]:
#1.ndim (no of dimensions)
#gives the type of dimension of an array.
print(a1.ndim) 
print(a2.ndim) 
print(a3.ndim)

1
2
3


In [18]:
#shape
#gives the number of rows and columns available in the dataset.
print(a1.shape) #(10,)
print(a2.shape) #(3,4)
print(a3.shape) #(2,2,2)  First 2 gives the number of array(no of 2d arrays) and second and third shows the rows and columns.

(10,)
(3, 4)
(2, 2, 2)


In [19]:
#size
#gives the number of items present in the array.
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [20]:
#Itemsize
#shows the size of an item taking place in memory.
#int32 = 4 bytes, and int64 = 8 bytes
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
4


In [21]:
#dtype
#gives the datatype.
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# Changing Datatypes


In [22]:
#astype:
#it is used to change the data type of existing datatype value. This is used when there is unnecessary datatype value in dataset.
#a way to optimize memory.
a3.dtype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# Array Operations

In [23]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [24]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
#Scalar Operations:

In [27]:
# Arithematic operation
#it performs operation with every array
a1 + 2
a1 - 2
a1 / 2
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [28]:
#Relational operator
#it checks every item in the array
a2 == 15
a2 != 15
a2 > 15
a2 < 15
a2 >=15
a2 <= 15

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [29]:
#Vector Operations:
#it is used when we apply operators on two numpy arrays.
#shape of arrays must be same while applying vector/tensor operations.
a1 + a2
a1 - a2
a1 / a2
a1 * a2
a1 ** a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

# Array Functions

In [30]:
a1 = np.random.random((3,3))
print(a1)
a1 = np.round(a1*100)
print(a1)
# a1*100

[[0.6393492  0.59026357 0.06205249]
 [0.59773444 0.0086942  0.26379503]
 [0.29378973 0.98539339 0.16216319]]
[[64. 59.  6.]
 [60.  1. 26.]
 [29. 99. 16.]]


In [31]:
#max/min/sum/product
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

99.0
1.0
360.0
1623532584960.0


In [32]:
#for getting max value from every row and column.
# 0-> column, 1-> row
print(np.max(a1, axis=1))
print(np.max(a1, axis=0))

[64. 60. 99.]
[64. 99. 26.]


In [33]:
#mean/median/std/var.
print(np.mean(a1, axis=1)) #gives the mean of every row
print(np.median(a1))       #gives the median of whole array
print(np.std(a1, axis=1))
print(np.var(a1, axis=1))

[43. 29. 48.]
29.0
[26.24245923 24.17988144 36.45088019]
[ 688.66666667  584.66666667 1328.66666667]


In [34]:
#Trigonometric funtions.
np.sin(a1)

array([[ 0.92002604,  0.63673801, -0.2794155 ],
       [-0.30481062,  0.84147098,  0.76255845],
       [-0.66363388, -0.99920683, -0.28790332]])

In [35]:
#dot Product
#The main criteria for dot product is the column size of first matrix must be equal to the row size of second matrix.
#The output will be the row size of first matrix X column size of secnod matrix.
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [36]:
#Log and exponents values.
print(np.log(a1))
print(np.exp(a1))

[[4.15888308 4.07753744 1.79175947]
 [4.09434456 0.         3.25809654]
 [3.36729583 4.59511985 2.77258872]]
[[6.23514908e+27 4.20121040e+25 4.03428793e+02]
 [1.14200739e+26 2.71828183e+00 1.95729609e+11]
 [3.93133430e+12 9.88903032e+42 8.88611052e+06]]


In [37]:
#round/floor/ceil

np.round(np.random.random((2,3))*100) #round of to the nearest number.
np.floor(np.random.random((2,3))*100) #6.9 = 6
np.ceil(np.random.random((2,3))*100)  #6.9 = 7

array([[74., 18., 24.],
       [21., 38., 74.]])

# Indexing and Slicing

In [38]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [39]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
#INDEXING: Fetching single item from the array.
a1[-1] 

9

In [41]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
a2[1,2]  #1-row, 2-column

6

In [43]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [44]:
a3[1,0,1]

5

In [45]:
a3[0,1,0]

2

In [46]:
a3[0,0,0]

0

In [47]:
a3[1,1,0]

6

In [48]:
#Slicing: Fetching Multiple items from the array.
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a1[2:5]

array([2, 3, 4])

In [50]:
a1[2:5:2]

array([2, 4])

In [51]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
a2[0,:]

array([0, 1, 2, 3])

In [53]:
a2[:,2]

array([ 2,  6, 10])

In [54]:
a2[1:,2]

array([ 6, 10])

In [55]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [56]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [57]:
a2[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [58]:
a2[1,::3]

array([4, 7])

In [59]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [60]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [61]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [62]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [63]:
a3[0,1]

array([3, 4, 5])

In [64]:
a3[1,:,1]

array([10, 13, 16])

In [65]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [66]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [67]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [70]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [71]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [72]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [73]:
for i in np.nditer(a3):
    print(i)
#prints every items in the array.

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [74]:
#reshape

In [75]:
#Transpose
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
np.transpose(a2)  #Or a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [77]:
#ravel
#Converts any dimension array into a 1D array.
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking  

In [78]:
#stacking refers to the concept of joining the no.of arrays.
#The only requirement is the shape of arrays must be same.
#Horizontal Stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)


In [79]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [81]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [82]:
np.hstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11, 20, 21, 22, 23]])

In [83]:
#Vertical Stacking.
np.vstack((a4,a5,a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [84]:
#It is opposite of stacking.
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
np.hsplit(a4,2)  #divides horizontally into 2 equal parts.

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [86]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [87]:
np.vsplit(a5,3) #Divides vertically into 3 equal parts.

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

The end of Fundamentals of Numpy....