In [5]:
import numpy as np

Task 13

Q-1 Create a null vector of size 10 but the fifth value which is 1.

In [9]:
a = np.nan*np.empty(10)  #np.empty(10) use to multipy with 'nan' value create a 10 'nan' values.
a[4]=1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [4]:
a = int(input())
b = int(input())
c = np.random.random((a,b))
print(c)
c.mean()

3
4
[[0.95270888 0.87162243 0.69304245 0.56327342]
 [0.30255937 0.99512188 0.51374298 0.05164527]
 [0.14033497 0.50090201 0.75421858 0.7300472 ]]


0.5891016198424591

Q-3Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.
Eg.-

[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]

In [ ]:
def create_array(a,b):
    a = np.ones((a,b))
    a[1:3,1:3] = 0
    return a

create_array(4,4)

Q-4 Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [ ]:
np.linspace(0,1,12)[1:11]

Q-5 Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
np.identity(3)
np.identity(4)

Q-6: Create a 5x5 matrix with row values ranging from 0 to 4.

In [ ]:
a = np.zeros((5,5))
a += np.arange(5)
a

Q-7: Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

point = np.array([2,3]) 

In [ ]:
np.random.randint(1,100,(10,2))


Q-8: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
np.unravel_index(100, (6,7,8))

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
a = input().strip().split()
np.array(a[::-1],dtype=float)