# np.sort 

In [2]:
#Returns the sorted copy of an array.
import numpy as np
a = np.random.randint(1,100,15)
a

array([61, 40, 73, 85, 86, 74, 54, 40, 14, 51,  7, 80, 57, 51, 84])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[12, 58, 64, 21],
       [48, 75, 75, 99],
       [95, 99, 26, 15],
       [17, 31,  5,  6],
       [20, 31,  9, 40],
       [28, 12, 63, 10]])

In [5]:
#Sort:
np.sort(a)

array([21, 24, 31, 37, 37, 43, 44, 48, 52, 54, 58, 65, 68, 87, 96])

In [4]:
np.sort(a)[::-1] #sorts in descending order, or reverse the list.

array([99, 90, 78, 76, 73, 68, 65, 64, 48, 45, 40, 40, 39, 28, 27])

In [5]:
np.sort(b)  #Row wise sorting of a 2D array.

array([[ 7, 57, 69, 85],
       [23, 43, 58, 63],
       [23, 37, 55, 71],
       [22, 30, 72, 76],
       [ 3, 63, 64, 88],
       [13, 61, 78, 93]])

In [6]:
np.sort(b, axis = 0)   #Column wise sorting.

array([[23, 23,  7,  3],
       [57, 30, 22, 13],
       [63, 61, 37, 55],
       [64, 69, 43, 58],
       [76, 71, 63, 72],
       [78, 88, 93, 85]])

# np.append()

In [7]:
#appends the value along the mentioned axis at the end of the array.
np.append(a,200)

array([ 90,  78,  73,  99,  28,  40,  27,  40,  48,  39,  65,  76,  45,
        68,  64, 200])

In [8]:
#To add a column in a existing 2d numpy array.
np.append(b,np.random.random((b.shape[0],1)), axis=1)

array([[57.        , 69.        ,  7.        , 85.        ,  0.78445636],
       [63.        , 23.        , 43.        , 58.        ,  0.81472975],
       [23.        , 71.        , 37.        , 55.        ,  0.73222935],
       [76.        , 30.        , 22.        , 72.        ,  0.51062359],
       [64.        , 88.        , 63.        ,  3.        ,  0.49077433],
       [78.        , 61.        , 93.        , 13.        ,  0.23883234]])

In [9]:
np.append(b,np.ones((b.shape[0],1)), axis=1)

array([[57., 69.,  7., 85.,  1.],
       [63., 23., 43., 58.,  1.],
       [23., 71., 37., 55.,  1.],
       [76., 30., 22., 72.,  1.],
       [64., 88., 63.,  3.,  1.],
       [78., 61., 93., 13.,  1.]])

# np.concatenate

In [10]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [11]:
np.concatenate((c,d), axis=0) #row wise concatenation, similar to horizontal stacking.

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
np.concatenate((c,d), axis=1) ##column wise concatenation, similar to vertical stacking. 

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique()

In [4]:
#With the help of unique(), we can get the unique values from an array.
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6,7,7])
f = np.array([[1,2,3,1],[1,2,3,2]])

In [14]:
e

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7])

In [6]:
np.unique(f,axis=0)  #gives the unique items from the array.

array([[1, 2, 3, 1],
       [1, 2, 3, 2]])

# np.expand_dims()

In [16]:
#With the help of this function we can get the expanded dimensions of an array.
a

array([90, 78, 73, 99, 28, 40, 27, 40, 48, 39, 65, 76, 45, 68, 64])

In [17]:
a.shape

(15,)

In [18]:
#after using the function it add the dimension or expand the dimension from 1D to 2D.
a_a = np.expand_dims(a, axis=0)
a_a

array([[90, 78, 73, 99, 28, 40, 27, 40, 48, 39, 65, 76, 45, 68, 64]])

In [19]:
a_a.shape

(1, 15)

In [20]:
a_a = np.expand_dims(a, axis=1)
a_a
print(a_a.shape)

(15, 1)


# np.where()

In [21]:
#Returns the indices of elements in an array where the given conditions is satisfied.
a

array([90, 78, 73, 99, 28, 40, 27, 40, 48, 39, 65, 76, 45, 68, 64])

In [22]:
#Find the index position of values greater than 50.
np.where(a>50)

(array([ 0,  1,  2,  3, 10, 11, 13, 14], dtype=int64),)

In [23]:
#Replace all values >50 with 0.
#np.where(condition,True, false)
np.where(a>50, 0, a)

array([ 0,  0,  0,  0, 28, 40, 27, 40, 48, 39,  0,  0, 45,  0,  0])

In [24]:
#Replace all even numbers with zeros.
np.where(a%2==0, 0,a)

array([ 0,  0, 73, 99,  0,  0, 27,  0,  0, 39, 65,  0, 45,  0,  0])

# np.argmax()

In [25]:
#returns the index position of max element of the array in a particular axis.
a

array([90, 78, 73, 99, 28, 40, 27, 40, 48, 39, 65, 76, 45, 68, 64])

In [26]:
np.argmax(a)  

3

In [27]:
b

array([[57, 69,  7, 85],
       [63, 23, 43, 58],
       [23, 71, 37, 55],
       [76, 30, 22, 72],
       [64, 88, 63,  3],
       [78, 61, 93, 13]])

In [28]:
np.argmax(b, axis=0)  #Gives column wise index of max number.

array([5, 4, 5, 0], dtype=int64)

In [29]:
np.argmax(b, axis=1)  #Gives row wise index of max number.

array([3, 0, 1, 0, 1, 2], dtype=int64)

# np.argmin()

In [30]:
#opposite of argmax().
np.argmin(a)

6

# np.cumsum()

In [31]:
#adding the previous sum to the next values and so on..
#This function gives the cummulative sum of an array over a given axis.
a

array([90, 78, 73, 99, 28, 40, 27, 40, 48, 39, 65, 76, 45, 68, 64])

In [32]:
np.cumsum(a)

array([ 90, 168, 241, 340, 368, 408, 435, 475, 523, 562, 627, 703, 748,
       816, 880])

In [33]:
b

array([[57, 69,  7, 85],
       [63, 23, 43, 58],
       [23, 71, 37, 55],
       [76, 30, 22, 72],
       [64, 88, 63,  3],
       [78, 61, 93, 13]])

In [34]:
np.cumsum(b, axis=0)  #If axis is not given, it will convert the 2D to 1D and then gives the sum

array([[ 57,  69,   7,  85],
       [120,  92,  50, 143],
       [143, 163,  87, 198],
       [219, 193, 109, 270],
       [283, 281, 172, 273],
       [361, 342, 265, 286]])

In [35]:
np.cumsum(b, axis=1)

array([[ 57, 126, 133, 218],
       [ 63,  86, 129, 187],
       [ 23,  94, 131, 186],
       [ 76, 106, 128, 200],
       [ 64, 152, 215, 218],
       [ 78, 139, 232, 245]])

# np.cumprod()

In [36]:
#This function gives the cummulative product.
a

array([90, 78, 73, 99, 28, 40, 27, 40, 48, 39, 65, 76, 45, 68, 64])

In [37]:
np.cumprod(a)

array([         90,        7020,      512460,    50733540,  1420539120,
         986989952,   878924928,   797258752,  -386285568,  2114732032,
          18628608,  1415774208,  -714670080, -1352925184,  -687865856])

# np.product()

In [38]:
#Used to compute the nth percentile of the given array.
a

array([90, 78, 73, 99, 28, 40, 27, 40, 48, 39, 65, 76, 45, 68, 64])

In [39]:
np.percentile(a,100) #100 per.-> max., 0 per.-> min.

99.0

In [40]:
np.percentile(a,0)

27.0

In [41]:
np.percentile(a,50)

64.0

# np.percentile

In [42]:
a

array([90, 78, 73, 99, 28, 40, 27, 40, 48, 39, 65, 76, 45, 68, 64])

In [71]:
np.percentile(a,50)

64.0

In [77]:
np.percentile(a,80)

80.60000000000002

# np.histogram()

In [43]:
#gives the number of items lying b/w the given range or called as bins.
a

array([90, 78, 73, 99, 28, 40, 27, 40, 48, 39, 65, 76, 45, 68, 64])

In [44]:
np.histogram(a, bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 0, 2, 1, 4, 0, 3, 3, 0, 2], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [45]:
np.histogram(a, bins=[0,50,100])

(array([7, 8], dtype=int64), array([  0,  50, 100]))

# np.corrcoef()

In [46]:
#Returns the correlation coefficient b/w two arrays.
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary, experience)  #coefficient lies b/w -1 to 1.

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# np.isin()

In [47]:
#We can see that one array having values are checked in different numpy arrays having different elements and differents sizes.
#Used to search multiple items in one time.
a

array([90, 78, 73, 99, 28, 40, 27, 40, 48, 39, 65, 76, 45, 68, 64])

In [48]:
items = [10,20,30,40,50,60,70,80,90,100]

np.isin(a, items)

array([ True, False, False, False, False,  True, False,  True, False,
       False, False, False, False, False, False])

In [49]:
a[np.isin(a, items)]

array([90, 40, 40])

# np.flip 

In [50]:
#Flips the array or reverse the array or makes the mirror image of an array.
a

array([90, 78, 73, 99, 28, 40, 27, 40, 48, 39, 65, 76, 45, 68, 64])

In [51]:
np.flip(a)

array([64, 68, 45, 76, 65, 39, 48, 40, 27, 40, 28, 99, 73, 78, 90])

In [52]:
b

array([[57, 69,  7, 85],
       [63, 23, 43, 58],
       [23, 71, 37, 55],
       [76, 30, 22, 72],
       [64, 88, 63,  3],
       [78, 61, 93, 13]])

In [53]:
np.flip(b)   #Two types of flipping occurs, first flips column wise and then flips the row wise.

array([[13, 93, 61, 78],
       [ 3, 63, 88, 64],
       [72, 22, 30, 76],
       [55, 37, 71, 23],
       [58, 43, 23, 63],
       [85,  7, 69, 57]])

In [54]:
np.flip(b,axis=0) #column flipping

array([[78, 61, 93, 13],
       [64, 88, 63,  3],
       [76, 30, 22, 72],
       [23, 71, 37, 55],
       [63, 23, 43, 58],
       [57, 69,  7, 85]])

In [55]:
np.flip(b,axis=1)  #row flipping

array([[85,  7, 69, 57],
       [58, 43, 23, 63],
       [55, 37, 71, 23],
       [72, 22, 30, 76],
       [ 3, 63, 88, 64],
       [13, 93, 61, 78]])

# np.put()

In [56]:
#This function replaces the index values in the array permanentally. 
#Can change multiple value at a same time
a

array([90, 78, 73, 99, 28, 40, 27, 40, 48, 39, 65, 76, 45, 68, 64])

In [57]:
#np.put(array_name,[index_positions],[new_index_values])
np.put(a, [0,1],[110,530])
a

array([110, 530,  73,  99,  28,  40,  27,  40,  48,  39,  65,  76,  45,
        68,  64])

# np.delete()

In [58]:
#Returns the new array with the deletion of sub-arrays along with the mentioned axis.
#This is temporary deletion.
a

array([110, 530,  73,  99,  28,  40,  27,  40,  48,  39,  65,  76,  45,
        68,  64])

In [59]:
#np.delete(array_name, index_positions_to_be_deleted)
np.delete(a,[0,2,4])

array([530,  99,  40,  27,  40,  48,  39,  65,  76,  45,  68,  64])

# Set Functions

In [60]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [61]:
#np.uninon1d(m,n)
np.union1d(m,n)  #Gives the union of two arrays but does not convert it to a set{}.

array([1, 2, 3, 4, 5, 6, 7])

In [62]:
#np.intersect1d()
np.intersect1d(m,n)

array([3, 4, 5])

In [63]:
#np.setdiff1d()
np.setdiff1d(m,n) #Gives the value which present in 'm' but not in 'n'.

array([1, 2])

In [64]:
np.setdiff1d(n,m)

array([6, 7])

In [65]:
#np.setxor1d()
#removes the common values b/1 m and n.
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [66]:
#np.in1d()
#shows that the value in present in the array.
np.in1d(m,1)

array([ True, False, False, False, False])

In [67]:



m[np.in1d(m,1)]

array([1])

In [68]:
np.in1d(m,10)

array([False, False, False, False, False])

# np.clip

In [69]:
#This function is used to limit the values in the array.
a

array([110, 530,  73,  99,  28,  40,  27,  40,  48,  39,  65,  76,  45,
        68,  64])

In [70]:
np.clip(a,a_min=25, a_max=75)

array([75, 75, 73, 75, 28, 40, 27, 40, 48, 39, 65, 75, 45, 68, 64])

##### np.sort(arr, axis=None):- Flatten the array and then sort it.

-array([ 6, 15, 48, 60, 63, 70, 74, 90, 92, 93, 93, 96])